// Generated by MARIGOLD-BATCH-APP (5-field outreach batch).
import type { MarigoldConfig } from "./config";

export const BUSINESS: MarigoldConfig = {
  "businessName": "Hideout Cafe",
  "location": "",
  "palette": "marigold-green",
  "fontSet": "fraunces-dmsans",
  "heroImage": "/hero.jpg",
  "aboutQuote": "We opened Hideout Cafe to be the kind of place we missed — somewhere warm, where the bread is real, the coffee is strong and nobody is in a rush.",
  "aboutAttribution": "— The owners",
  "phone": "0131 466 1714",
  "email": "hello@hideoutcafe.co.uk",
  "address": [
    "5 Upper Bow Edinburgh"
  ]
};
